### ISSUE TITLE
error in main.py

### ISSUE THREAD

**Issue by woo1** [jdlamstein/happybot#2]
Thanks for sharing your code.

Traceback (most recent call last):
  File "main_pc.py", line 271, in <module>
    facsUp = modelUp.run(facialMotionUp)
  File "/happybot/happybot/tf_helper.py", line 53, in run
    return self.sess.run(self.activation, feed_dict={"x:0": data})
  File "/happybot/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/happybot/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 11) for Tensor 'x:0', which has shape '(?, 19)'

error raises in this line
`facsUp = modelUp.run(facialMotionUp)`
https://github.com/jdlamstein/happybot/blob/master/happybot/main.py#L286

Maybe checkpoint file (nn/top/model-3000) is wrong.
How can I solve this?

**Comment by alarazin** [comment]
@woo1 hi, I have the same problem. Could you solve it?

**Comment by nhanvonguyen99** [comment]
@alarazin Hi, I have the same problem. Could you solve it?

**Comment by alarazin** [comment]
@vonhanyt123 hello, I assume the trained model that he uploaded is an old one.

While assigning facialMotionUp :
facialMotionUp = np.reshape(feat.UpperFaceFeatures(neutralFeaturesUpper, newFeaturesUpper),(-1,11))

I changed 11 to 19:
facialMotionUp = np.reshape(feat.UpperFaceFeatures(neutralFeaturesUpper, newFeaturesUpper),(-1,19))

and it works.

**Comment by nhanvonguyen99** [comment]
@alarazin Thank you for your assitance

**Comment by StevenJered** [comment]
hi, I got same problem with @vonhanyt123 .
but after I changed the 11 to 19, it still not works.
